Algoritmo "idadedoatleta"
// Autor(a)    : Francisco Sousa
// Data atual  : 28/09/2017
Var
idade : inteiro
Inicio
escreva ("Qual é a idade do atleta?")

leia(idade)

escolha idade
caso 5 ate 7
 escreva ("infantil A")
caso 8 ate 10
 escreva ("infantil B")
caso 11 ate 13
 escreva ("juvenil A")
caso 14 ate 17
 escreva ("juvenil B")
caso 18 ate 1000
 escreva ("senior")

Fimalgoritmo